# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#publishing-using-gradle

name: Deploy on Raspberry PI 1

on:
  workflow_run:
      workflows: ["Gradle Package"]
      types:
        - completed

jobs:
  build:
    runs-on: ["self-hosted", "rpi1"]

    steps:
    - name: Download 'iscte.saiiot2020.accelkart'
      uses: dawidd6/action-download-artifact@v2.10.0
      with:
        workflow: gradle-publish.yml
        name: 'iscte.saiiot2020.accelkart'

    - name: Display structure of downloaded files
      run: ls -R